databases:
  - name: helios-db
    databaseName: helios
    user: helios
    region: oregon

services:
  - type: web
    name: helios
    runtime: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helios-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true 